# Generated by Django 4.1 on 2022-10-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='newimages/')),
            ],
        ),
    ]
