# Generated by Django 4.1 on 2022-10-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=6)),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(upload_to='newimages/')),
            ],
        ),
    ]
