# Generated by Django 4.1 on 2022-11-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_student_year_alter_teacher_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
