# Generated by Django 4.1 on 2022-11-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_course_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
    ]
