# Generated by Django 4.1 on 2022-11-04 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='desc',
        ),
    ]
