# Generated by Django 4.1 on 2022-11-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_teachers_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
