# Generated by Django 4.1 on 2022-11-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='newimages/')),
            ],
        ),
    ]
